// Code generated by "stringer -type=GameState"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateRunning-1]
	_ = x[StateMainMenu-2]
	_ = x[StateInstructions-3]
	_ = x[StateGameOver-4]
	_ = x[StateQuitGame-5]
}

const _GameState_name = "StateRunningStateMainMenuStateInstructionsStateGameOverStateQuitGame"

var _GameState_index = [...]uint8{0, 12, 25, 42, 55, 68}

func (i GameState) String() string {
	i -= 1
	if i < 0 || i >= GameState(len(_GameState_index)-1) {
		return "GameState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _GameState_name[_GameState_index[i]:_GameState_index[i+1]]
}
